// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: proto/hermeticum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorldEvent_WorldEventType int32

const (
	WorldEvent_WHISPER   WorldEvent_WorldEventType = 0 // someone or something sent a private message to user
	WorldEvent_OVERHEARD WorldEvent_WorldEventType = 1 // someone or something in the same room said something out loud
	WorldEvent_EMOTE     WorldEvent_WorldEventType = 2 // someone or something in the same room performed an action
	WorldEvent_PRINT     WorldEvent_WorldEventType = 3 // just a string that should be printed (ie, "you hear noises in a nearby room")
	WorldEvent_GLOBAL    WorldEvent_WorldEventType = 4 // the system sent out a PSA
	WorldEvent_SHOUT     WorldEvent_WorldEventType = 5 // a user spammed the world
	WorldEvent_ENTER     WorldEvent_WorldEventType = 6 // someone or something has appeared in room
	WorldEvent_LEAVE     WorldEvent_WorldEventType = 7 // someone or something has left room
)

// Enum value maps for WorldEvent_WorldEventType.
var (
	WorldEvent_WorldEventType_name = map[int32]string{
		0: "WHISPER",
		1: "OVERHEARD",
		2: "EMOTE",
		3: "PRINT",
		4: "GLOBAL",
		5: "SHOUT",
		6: "ENTER",
		7: "LEAVE",
	}
	WorldEvent_WorldEventType_value = map[string]int32{
		"WHISPER":   0,
		"OVERHEARD": 1,
		"EMOTE":     2,
		"PRINT":     3,
		"GLOBAL":    4,
		"SHOUT":     5,
		"ENTER":     6,
		"LEAVE":     7,
	}
)

func (x WorldEvent_WorldEventType) Enum() *WorldEvent_WorldEventType {
	p := new(WorldEvent_WorldEventType)
	*p = x
	return p
}

func (x WorldEvent_WorldEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorldEvent_WorldEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hermeticum_proto_enumTypes[0].Descriptor()
}

func (WorldEvent_WorldEventType) Type() protoreflect.EnumType {
	return &file_proto_hermeticum_proto_enumTypes[0]
}

func (x WorldEvent_WorldEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorldEvent_WorldEventType.Descriptor instead.
func (WorldEvent_WorldEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_hermeticum_proto_rawDescGZIP(), []int{2, 0}
}

type PingMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	When string `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"` // when the client created the ping payload
}

func (x *PingMsg) Reset() {
	*x = PingMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hermeticum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMsg) ProtoMessage() {}

func (x *PingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermeticum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMsg.ProtoReflect.Descriptor instead.
func (*PingMsg) Descriptor() ([]byte, []int) {
	return file_proto_hermeticum_proto_rawDescGZIP(), []int{0}
}

func (x *PingMsg) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verb string `protobuf:"bytes,1,opt,name=verb,proto3" json:"verb,omitempty"`
	Rest string `protobuf:"bytes,2,opt,name=rest,proto3" json:"rest,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hermeticum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermeticum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_hermeticum_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *Command) GetRest() string {
	if x != nil {
		return x.Rest
	}
	return ""
}

type WorldEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   WorldEvent_WorldEventType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.WorldEvent_WorldEventType" json:"type,omitempty"`
	Source *string                   `protobuf:"bytes,2,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Text   *string                   `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
}

func (x *WorldEvent) Reset() {
	*x = WorldEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hermeticum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEvent) ProtoMessage() {}

func (x *WorldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermeticum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEvent.ProtoReflect.Descriptor instead.
func (*WorldEvent) Descriptor() ([]byte, []int) {
	return file_proto_hermeticum_proto_rawDescGZIP(), []int{2}
}

func (x *WorldEvent) GetType() WorldEvent_WorldEventType {
	if x != nil {
		return x.Type
	}
	return WorldEvent_WHISPER
}

func (x *WorldEvent) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *WorldEvent) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	When  string `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`   // timestamp of pong creation
	Delta string `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"` // timestamp of delta between pingmsg.when and its receipt
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hermeticum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermeticum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_hermeticum_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *Pong) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

var File_proto_hermeticum_proto protoreflect.FileDescriptor

var file_proto_hermeticum_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x69, 0x63,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1d, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x31,
	0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x65, 0x72,
	0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x65, 0x72, 0x62, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x74, 0x22, 0xfd, 0x01, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x22, 0x6f, 0x0a, 0x0e,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x57, 0x48, 0x49, 0x53, 0x50, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x56, 0x45, 0x52, 0x48, 0x45, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d,
	0x4f, 0x54, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x49, 0x4e, 0x54, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x48, 0x4f, 0x55, 0x54, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x54, 0x45, 0x52,
	0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x07, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x30, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x32, 0x66, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x12, 0x34, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x1a, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x6c, 0x6d, 0x69, 0x62,
	0x6d, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x75, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hermeticum_proto_rawDescOnce sync.Once
	file_proto_hermeticum_proto_rawDescData = file_proto_hermeticum_proto_rawDesc
)

func file_proto_hermeticum_proto_rawDescGZIP() []byte {
	file_proto_hermeticum_proto_rawDescOnce.Do(func() {
		file_proto_hermeticum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hermeticum_proto_rawDescData)
	})
	return file_proto_hermeticum_proto_rawDescData
}

var file_proto_hermeticum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hermeticum_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_hermeticum_proto_goTypes = []any{
	(WorldEvent_WorldEventType)(0), // 0: proto.WorldEvent.WorldEventType
	(*PingMsg)(nil),                // 1: proto.PingMsg
	(*Command)(nil),                // 2: proto.Command
	(*WorldEvent)(nil),             // 3: proto.WorldEvent
	(*Pong)(nil),                   // 4: proto.Pong
}
var file_proto_hermeticum_proto_depIdxs = []int32{
	0, // 0: proto.WorldEvent.type:type_name -> proto.WorldEvent.WorldEventType
	2, // 1: proto.GameWorld.ClientInput:input_type -> proto.Command
	1, // 2: proto.GameWorld.Ping:input_type -> proto.PingMsg
	3, // 3: proto.GameWorld.ClientInput:output_type -> proto.WorldEvent
	4, // 4: proto.GameWorld.Ping:output_type -> proto.Pong
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hermeticum_proto_init() }
func file_proto_hermeticum_proto_init() {
	if File_proto_hermeticum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hermeticum_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PingMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hermeticum_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hermeticum_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WorldEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hermeticum_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_hermeticum_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hermeticum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hermeticum_proto_goTypes,
		DependencyIndexes: file_proto_hermeticum_proto_depIdxs,
		EnumInfos:         file_proto_hermeticum_proto_enumTypes,
		MessageInfos:      file_proto_hermeticum_proto_msgTypes,
	}.Build()
	File_proto_hermeticum_proto = out.File
	file_proto_hermeticum_proto_rawDesc = nil
	file_proto_hermeticum_proto_goTypes = nil
	file_proto_hermeticum_proto_depIdxs = nil
}
